version: '3.9'

services:
# start the server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

  # start the mongodb service as container
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGODB_DATABASE=feed

  # start the redis service as container
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
